### ISSUE TITLE
Inconsistent crash on launch - Unsupported root entry "credits" at line 10 column 14

### ISSUE THREAD

**Issue by twenty41** [nvb-uy/Necronomicon#2]
[2023-11-24-5.log](https://github.com/nvb-uy/Necronomicon/files/13462453/2023-11-24-5.log)
Happened once

**Comment by nvb-uy** [comment]
that's not the crash cause, json entries in the fabric mod json don't cause crashes, your issue is caused by backpacked

**Comment by twenty41** [comment]
how do you determine that? server crashed again and all i know is it says NECRONOMICON API HAS INVALID ENTRIES IN ITS MOD JSON at the top

**Comment by nvb-uy** [comment]
Because that error is NOT a crash error, it's just a warning. You don't have to "parse 577 lines of code" because there's no code there, logs are just logs, information.

Your crash error will appear at the bottom, as I told you, it's caused by backpacked:
```
ava.lang.IllegalStateException: Config property is not linked yet
	at com.mrcrayfish.framework.api.config.AbstractProperty.get(AbstractProperty.java:89) ~[framework-fabric-1.20.1-0.6.16.jar:?]
	at com.mrcrayfish.backpacked.util.ClientUtils.createBackpackTooltip(ClientUtils.java:23) ~[backpacked-fabric-1.20.1-2.2.7.jar:?]
	at com.mrcrayfish.backpacked.item.BackpackItem.method_7851(BackpackItem.java:62) ~[backpacked-fabric-1.20.1-2.2.7.jar:?]
```
